class AwardService
  AL_TEAM_IDS  = [108, 110, 111, 114, 116, 117, 118, 133, 136, 139, 140, 141, 142, 145, 147].freeze
  SS_POSITIONS = %w[C 1B 2B 3B SS OF DH].freeze
  POSITION_NORM = {
    "C"  => "C",  "1B" => "1B", "2B" => "2B", "3B" => "3B", "SS" => "SS",
    "LF" => "OF", "CF" => "OF", "RF" => "OF", "OF" => "OF", "DH" => "DH"
  }.freeze

  class << self
    def awards_data(league)
      insight = SimulationInsight.find_by(
        simulation_league_id: league.id,
        subject_type:         "awards",
        subject_id:           league.id
      )
      return nil unless insight

      data = JSON.parse(insight.bullets_json)
      # Handle old format where full OpenAI response (with request_id/model/output wrapper) was stored
      data.key?("output") && data["output"].is_a?(Hash) ? data["output"] : data
    rescue JSON::ParserError
      nil
    end

    def generate_awards(league)
      stats   = SimulationPlayerStat.where(simulation_league_id: league.id)
      pos_map = build_position_map(league)
      ctx     = SimulationSeasonContext.for_league(league)

      return { error: "No stats available yet — the season has not started." } if ctx[:phase] == :pre_season

      candidates = build_candidates(stats, pos_map)
      payload    = build_prompt_payload(candidates).merge(season_context: ctx)

      attempts = 0
      begin
        attempts += 1
        result = OpenAi::Client.new.json_completion(
          system_prompt:    awards_system_prompt(ctx),
          user_payload:     payload.to_json,
          interaction_type: "sim_season_awards",
          metadata:         { league_id: league.id },
          temperature:      0.4,
          timeout:          90
        )
      rescue => e
        raise if attempts >= 2
        Rails.logger.warn "[AwardService] Attempt #{attempts} failed (#{e.message}), retrying"
        retry
      end

      # Store only the structured output, not the full OpenAI wrapper (request_id, model, usage)
      award_data = result[:output] || result["output"] || result

      SimulationInsight.upsert(
        {
          simulation_league_id: league.id,
          subject_type:         "awards",
          subject_id:           league.id,
          narrative:            "Season awards generated by AI committee",
          bullets_json:         award_data.to_json,
          generated_at:         Time.current,
          created_at:           Time.current,
          updated_at:           Time.current
        },
        unique_by: :idx_sim_insights_lookup
      )

      award_data
    end

    private

    def build_position_map(league)
      map = {}
      league.simulation_rosters.each do |roster|
        JSON.parse(roster.roster_json || "[]").each do |p|
          normalized = POSITION_NORM[p["position"].to_s.upcase]
          map[p["id"].to_i] = normalized if normalized
        end
      rescue JSON::ParserError
        next
      end
      map
    end

    def eligibility_thresholds(stats)
      max_g = [stats.where(player_type: "batter").maximum(:g).to_i, 1].max
      {
        min_ab:       [[max_g * 2, 25].max, 400].min,
        min_outs:     [[max_g * 1, 10].max, 486].min,
        min_gs:       [[max_g / 20, 1].max, 32].min,
        min_reliever: [[max_g / 8,  3].max, 60].min
      }
    end

    def build_candidates(stats, pos_map)
      t            = eligibility_thresholds(stats)
      batters      = stats.where(player_type: "batter").select { |s| s.ab >= t[:min_ab] }
      starters     = stats.where(player_type: "pitcher").select { |s| s.gs >= t[:min_gs] && s.outs_pitched >= t[:min_outs] }
      relievers    = stats.where(player_type: "pitcher").select { |s| s.gs <= 2 && s.g_pitched >= t[:min_reliever] }
      all_pitchers = stats.where(player_type: "pitcher").to_a
      ss_batters   = stats.where(player_type: "batter").select { |s| s.ab >= [t[:min_ab] / 2, 15].max }

      {
        mvp:            al_nl_split(top_batters(batters, :ops, 10)),
        cy_young:       al_nl_split(top_pitchers(starters, :era, 10, asc: true)),
        batting_title:  al_nl_split(top_batters(batters, :avg, 5)),
        hr_leader:      al_nl_split(top_batters(batters, :hr, 5)),
        rbi_leader:     al_nl_split(top_batters(batters, :rbi, 5)),
        era_title:      al_nl_split(top_pitchers(starters, :era, 5, asc: true)),
        k_leader:       top_pitchers(all_pitchers, :k_pitched, 5),
        saves_leader:   top_pitchers(all_pitchers, :sv, 5),
        reliever:       top_pitchers(relievers, :era, 5, asc: true),
        silver_slugger: silver_slugger_candidates(ss_batters, pos_map)
      }
    end

    def silver_slugger_candidates(batters, pos_map)
      by_pos = SS_POSITIONS.each_with_object({}) { |p, h| h[p] = [] }
      batters.each do |s|
        pos = pos_map[s.player_id]
        by_pos[pos] << serialize_batter(s) if pos && by_pos.key?(pos)
      end
      by_pos.transform_values do |players|
        top = players.sort_by { |p| -ops_from_serialized(p) }.first(3)
        al_nl_split(top)
      end
    end

    def ops_from_serialized(p)
      s  = p[:stats]
      return 0 unless s
      ab = s[:ab].to_f
      bb = s[:bb].to_f
      h  = s[:h].to_f
      hr = s[:hr].to_f
      obp = (ab + bb) > 0 ? (h + bb) / (ab + bb) : 0
      slg = ab > 0 ? (h + hr) / ab : 0
      obp + slg
    end

    def al_nl_split(players)
      {
        al: players.select { |p| AL_TEAM_IDS.include?(p[:team_id]) },
        nl: players.reject { |p| AL_TEAM_IDS.include?(p[:team_id]) }
      }
    end

    def top_batters(batters, stat, n)
      batters.sort_by { |s| -computed_rate(s, stat) }.first(n).map { |s| serialize_batter(s) }
    end

    def top_pitchers(pitchers, stat, n, asc: false)
      sorted = pitchers.sort_by { |s| computed_rate(s, stat) }
      sorted = sorted.reverse unless asc
      sorted.first(n).map { |s| serialize_pitcher(s) }
    end

    def computed_rate(s, stat)
      case stat
      when :avg       then s.ab > 0 ? s.h.to_f / s.ab : 0
      when :ops       then batter_obp(s) + batter_slg(s)
      when :era       then s.outs_pitched > 0 ? (s.er * 27.0) / s.outs_pitched : 99.0
      when :k_pitched then s.k_pitched.to_f
      when :sv        then s.sv.to_f
      when :hr        then s.hr.to_f
      when :rbi       then s.rbi.to_f
      else 0
      end
    end

    def batter_obp(s)
      denom = s.ab + s.bb
      denom > 0 ? (s.h + s.bb).to_f / denom : 0
    end

    def batter_slg(s)
      s.ab > 0 ? (s.h + s.hr).to_f / s.ab : 0
    end

    def pitcher_era(s)
      s.outs_pitched > 0 ? (s.er * 27.0 / s.outs_pitched).round(2) : 99.0
    end

    def pitcher_whip(s)
      s.outs_pitched > 0 ? ((s.h_allowed + s.bb_allowed) / (s.outs_pitched / 3.0)).round(2) : 99.0
    end

    def serialize_batter(s)
      avg       = s.ab > 0 ? (s.h.to_f / s.ab).round(3) : 0
      ops       = (batter_obp(s) + batter_slg(s)).round(3)
      team_meta = MlbApiService::TEAM_META[s.team_id] || {}
      {
        player_id:   s.player_id,
        player_name: s.player_name,
        team_id:     s.team_id,
        team_abbr:   team_meta[:abbr],
        stats:       { avg:, hr: s.hr, rbi: s.rbi, ops:, g: s.g, ab: s.ab, h: s.h, bb: s.bb }
      }
    end

    def serialize_pitcher(s)
      ip        = "#{s.outs_pitched / 3}.#{s.outs_pitched % 3}"
      team_meta = MlbApiService::TEAM_META[s.team_id] || {}
      {
        player_id:   s.player_id,
        player_name: s.player_name,
        team_id:     s.team_id,
        team_abbr:   team_meta[:abbr],
        stats:       {
          era: pitcher_era(s), whip: pitcher_whip(s),
          ip:, w: s.w, l: s.l, k: s.k_pitched, sv: s.sv, gs: s.gs
        }
      }
    end

    def build_prompt_payload(candidates)
      candidates.transform_values do |val|
        if val.is_a?(Hash) && val.key?(:al)
          { al: val[:al], nl: val[:nl] }
        else
          val
        end
      end
    end

    def awards_system_prompt(ctx)
      phase = ctx[:phase]
      notes = ctx[:milestone_notes]
      season_complete = phase == :complete

      role, tone = if season_complete
        [
          "the official awards committee for a completed MLB season",
          "The season is over. Select a definitive winner for each award and announce it with authority. " \
          "Use past tense — 'led', 'posted', 'claimed'. Write each rationale as a formal award announcement."
        ]
      elsif %i[stretch_run final_weeks].include?(phase)
        [
          "a baseball analyst tracking the award races in the final weeks of the season",
          "The races are nearly decided but not official. Use language like 'has built a commanding lead', " \
          "'appears to be the frontrunner', 'is difficult to catch at this point'. Do NOT declare winners. " \
          "Rationale should convey urgency — the chase is almost over."
        ]
      elsif phase == :midseason
        [
          "a baseball analyst reporting on award races at the All-Star break",
          "We are at the midpoint of the season — no winner has been decided. Use language like " \
          "'leads the race', 'is the frontrunner', 'has emerged as the top candidate', 'is on pace for'. " \
          "Rationale should be analytical and forward-looking. Mention if the race is tight or a runaway."
        ]
      else
        [
          "a baseball analyst tracking the early award races",
          "It is early in the season — small samples apply, but trends are emerging. Use cautious, " \
          "forward-looking language: 'is off to a strong start', 'leads the early race', 'is pacing for', " \
          "'has positioned themselves'. Acknowledge the season still has a long way to go."
        ]
      end

      milestone_str = notes.any? ? "\n\nContext: #{notes.join(' ')}" : ""

      <<~PROMPT.strip
        You are #{role}.#{milestone_str}
        You will receive top statistical candidates for each award category.
        #{tone}
        Treat the statistics as real — do not reference simulation or AI.
        Return ONLY valid JSON with no markdown, no code fences, matching this exact schema:
        {
          "mvp":           { "al": { "winner": <player>, "finalists": [<player>,...], "rationale": "..." }, "nl": { ... } },
          "cy_young":      { "al": { ... }, "nl": { ... } },
          "batting_title": { "al": { ... }, "nl": { ... } },
          "hr_leader":     { "al": { ... }, "nl": { ... } },
          "rbi_leader":    { "al": { ... }, "nl": { ... } },
          "era_title":     { "al": { ... }, "nl": { ... } },
          "k_leader":      { "overall": { "winner": <player>, "finalists": [...], "rationale": "..." } },
          "saves_leader":  { "overall": { ... } },
          "reliever":      { "overall": { ... } },
          "silver_slugger": {
            "C":  { "al": { "winner": <player>, "finalists": [], "rationale": "..." }, "nl": { ... } },
            "1B": { "al": { ... }, "nl": { ... } },
            "2B": { "al": { ... }, "nl": { ... } },
            "3B": { "al": { ... }, "nl": { ... } },
            "SS": { "al": { ... }, "nl": { ... } },
            "OF": { "al": { ... }, "nl": { ... } },
            "DH": { "al": { ... }, "nl": { ... } }
          }
        }
        For silver_slugger, select the best offensive player (by OPS) at each position within each league.
        Each <player> object: { "player_id": N, "player_name": "...", "team_abbr": "...", "stats": { ... } }
        If a league has no eligible candidates for an award or position, set that entry to null.
      PROMPT
    end
  end
end
