class PlayoffAwardService
  MIN_AB          = 5
  MIN_OUTS_PITCHED = 3

  class << self
    def playoff_awards_data(league)
      insight = SimulationInsight.find_by(
        simulation_league_id: league.id,
        subject_type:         "playoff_awards",
        subject_id:           league.id
      )
      return nil unless insight
      JSON.parse(insight.bullets_json)
    rescue JSON::ParserError
      nil
    end

    def generate_playoff_awards(league)
      ws    = league.simulation_playoff_series.find_by(round: "ws")
      al_cs = league.simulation_playoff_series.find_by(round: "cs", league: "AL")
      nl_cs = league.simulation_playoff_series.find_by(round: "cs", league: "NL")

      unless ws&.complete? && al_cs&.complete? && nl_cs&.complete?
        return { error: "Playoffs not complete — run all rounds first" }
      end

      all_series = league.simulation_playoff_series.order(:id)
      ws_winner_abbr = ws.winner_team_id == ws.home_team_id ? ws.home_team_abbr : ws.away_team_abbr

      payload = {
        ws_mvp:   series_candidates(league, ws,    ws.winner_team_id),
        alcs_mvp: series_candidates(league, al_cs, al_cs.winner_team_id),
        nlcs_mvp: series_candidates(league, nl_cs, nl_cs.winner_team_id),
        series_results: {
          ws:   series_summary(ws),
          alcs: series_summary(al_cs),
          nlcs: series_summary(nl_cs),
        },
        full_bracket:  all_series.map { |s| full_series_summary(s, ws_winner_abbr) },
        champion_abbr: ws_winner_abbr,
      }

      attempts = 0
      begin
        attempts += 1
        result = OpenAi::Client.new.json_completion(
          system_prompt:    awards_system_prompt,
          user_payload:     payload.to_json,
          interaction_type: "playoff_awards",
          metadata:         { league_id: league.id },
          temperature:      0.4,
          timeout:          60
        )
      rescue => e
        raise if attempts >= 2
        Rails.logger.warn "[PlayoffAwardService] Attempt #{attempts} failed (#{e.message}), retrying"
        retry
      end

      awards = result.is_a?(Hash) && result.key?(:output) ? result[:output] : result

      SimulationInsight.upsert(
        {
          simulation_league_id: league.id,
          subject_type:         "playoff_awards",
          subject_id:           league.id,
          narrative:            "Playoff awards generated by AI committee",
          bullets_json:         awards.to_json,
          generated_at:         Time.current,
          created_at:           Time.current,
          updated_at:           Time.current,
        },
        unique_by: :idx_sim_insights_lookup
      )

      awards
    end

    private

    def series_candidates(league, series, winner_team_id)
      stats = SimulationPlayoffPlayerStat
                .where(simulation_playoff_series_id: series.id, team_id: winner_team_id)

      batters  = stats.where(player_type: "batter").to_a
                      .select { |s| s.ab >= MIN_AB }
                      .sort_by { |s| -s.ops }
                      .first(8)
                      .map { |s| serialize_batter(s) }

      pitchers = stats.where(player_type: "pitcher").to_a
                      .select { |s| s.outs_pitched >= MIN_OUTS_PITCHED }
                      .sort_by { |s| s.era }
                      .first(5)
                      .map { |s| serialize_pitcher(s) }

      { batters:, pitchers: }
    end

    def series_summary(series)
      winner_abbr = series.winner_team_id == series.home_team_id ? series.home_team_abbr : series.away_team_abbr
      {
        home:        series.home_team_abbr,
        away:        series.away_team_abbr,
        home_wins:   series.home_wins,
        away_wins:   series.away_wins,
        winner:      winner_abbr,
      }
    end

    def full_series_summary(series, champion_abbr)
      winner_abbr = series.winner_team_id == series.home_team_id ? series.home_team_abbr : series.away_team_abbr
      round_label = { "wc" => "Wild Card", "ds" => "Division Series", "cs" => "Championship Series", "ws" => "World Series" }
      champion_side = [series.home_team_abbr, series.away_team_abbr].include?(champion_abbr) ? champion_abbr : nil
      {
        round:         round_label[series.round] || series.round,
        league:        series.league,
        home:          series.home_team_abbr,
        away:          series.away_team_abbr,
        home_wins:     series.home_wins,
        away_wins:     series.away_wins,
        winner:        winner_abbr,
        games_played:  series.home_wins + series.away_wins,
        champion_in_series: champion_side,
      }
    end

    def serialize_batter(s)
      team_meta = MlbApiService::TEAM_META[s.team_id] || {}
      {
        player_id:   s.player_id,
        player_name: s.player_name,
        team_abbr:   team_meta[:abbr] || s.team_id.to_s,
        stats:       { avg: s.avg, hr: s.hr, rbi: s.rbi, ops: s.ops,
                       ab: s.ab, h: s.h, bb: s.bb, g: s.g },
      }
    end

    def serialize_pitcher(s)
      team_meta = MlbApiService::TEAM_META[s.team_id] || {}
      {
        player_id:   s.player_id,
        player_name: s.player_name,
        team_abbr:   team_meta[:abbr] || s.team_id.to_s,
        stats:       { era: s.era, whip: s.whip, ip: s.ip_display,
                       k: s.k_pitched, w: s.w, sv: s.sv, gs: s.gs },
      }
    end

    def awards_system_prompt
      <<~PROMPT.strip
        You are the official postseason awards committee for an MLB season.
        You will receive:
        1. Top statistical candidates for the World Series MVP, ALCS MVP, and NLCS MVP.
        2. The champion team abbreviation and the full playoff bracket showing every series result.

        Tasks:
        A) For each MVP award, select one winner and up to 2 finalists from the provided candidates.
           Each award covers only the games in that specific series.
           Write a 2-3 sentence rationale in the style of an official league announcement.
        B) Write a championship_narrative for the World Series champion:
           - "headline": 8-12 words capturing the essence of their postseason run (punchy, present-tense feel)
           - "body": 3-4 sentences tracing their full journey — which opponents they defeated, any adversity (close series, elimination games), and what defined this team's championship.

        Write in a direct, analytical tone. Do not use the words "simulated" or "simulation".
        Return ONLY valid JSON matching this exact schema:
        {
          "ws_mvp":   { "winner": <player>, "finalists": [<player>, ...], "rationale": "..." },
          "alcs_mvp": { "winner": <player>, "finalists": [<player>, ...], "rationale": "..." },
          "nlcs_mvp": { "winner": <player>, "finalists": [<player>, ...], "rationale": "..." },
          "championship_narrative": { "headline": "...", "body": "..." }
        }
        Each <player>: { "player_id": N, "player_name": "...", "team_abbr": "...", "stats": { ... } }
        If no eligible candidates exist for an award, set that award to null.
      PROMPT
    end
  end
end
